### ISSUE TITLE
Merge the function of open file

### ISSUE THREAD

**Issue by Megnji** [Megnji/Lightning#4]
While reading a file, it should update both plot panel and information panel, at current stage it only updated information panel.

Upon finishing this issue, open file item's response shall call "updatePlotPanel(String info)" method in a static way. Thus, PlotPanel.updatePanel(String info) should be called. 

Where the string "info" should contains  no redundant information.

**Comment by wykbill** [comment]
embedding data is sent to plot function with a string array called info[].
